# Generated by Django 4.1.1 on 2022-10-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ITEM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("desc", models.TextField()),
                ("img", models.TextField()),
                ("price", models.TextField()),
                ("is_in_cart", models.BooleanField()),
                ("subsection", models.TextField()),
                ("section", models.TextField()),
            ],
        ),
    ]
