INITIAL_ITEM_INFO = [
    {
        "name": "Diamond Pickaxe",
        "desc": "This item is pretty self explanatory, its a pickaxe made of diamonds from the video game Minecraft.",
        "img": "pickaxe.png",
        "price": "180,000",
        "is_in_cart": True,
        "subsection": "Minecraft",
        "section": "Video-Games",
    },
    {
        "name": "Maxwell's Notebook",
        "desc": "This item is the notebook from the game Scribblenauts, the notebook that makes anything you write in it real.",
        "img": "maxWellsNotebook.png",
        "price": "999,999,999,999",
        "is_in_cart": False,
        "subsection": "Scribblenauts",
        "section": "Video-Games",
    },
    {
        "name": "Sweet Roll",
        "desc": "The Sweet Roll is a pastry-like treat that can be found in almost everywhere in Skyrim",
        "img": "sweetrole.png",
        "price": "4.99",
        "is_in_cart": False,
        "subsection": "Skyrim",
        "section": "Video-Games",
    },
    {
        "name": "Mehrunes' Razor",
        "desc": "Extremely powerful Deadric artifact crafted Mehrunes Dagon that has a chance to instantly kill any opponent",
        "img": "mehrunesRazor.png",
        "price": "99,000.00",
        "is_in_cart": False,
        "subsection": "Skyrim",
        "section": "Video-Games",
    },
    {
        "name": "Mr. Meeseeks Box",
        "desc": "Gadget that creates a Mr Meeseeks for the purpose of completeing one given object",
        "img": "mrMeeseeksBox.png",
        "price": "9,000.00",
        "is_in_cart": False,
        "subsection": "Rick-and-Morty",
        "section": "Movies-Series",
    },
    {
        "name": "C137's Portal Gun",
        "desc": "Gadget that allows user(s) to travel to different universes/dimensions/realities.",
        "img": "portalGun.png",
        "price": "99,999,999.99",
        "is_in_cart": False,
        "subsection": "Rick-and-Morty",
        "section": "Movies-Series",
    },
    {
        "name": "Archmeaster Walgrave's Key",
        "desc": "Can unlock any door in the Citadel granting you unlimited knowledge",
        "img": "not yet done",
        "price": "299.00",
        "is_in_cart": False,
        "subsection": "Game-Of-Thrones",
        "section": "Movies-Series",
    },
    {
        "name": "The Renaissance Vase",
        "desc": "this item is the vase from the anime Oran Highschool Host Club",
        "img": "vase.webp",
        "price": "8,000,000",
        "is_in_cart": False,
        "subsection": "Oran-Highschool-Host-Club",
        "section": "Anime",
    },
    {
        "name": "Gomu Gomu no Mi",
        "desc": "This item is whats known as a devil's fruit the anime called One Piece",
        "img": "devil fruit.jpg",
        "price": "5,000,000,000",
        "is_in_cart": False,
        "subsection": "One-Piece",
        "section": "Anime",
    },
    {
        "name": "Kurapika's Judgement Chain",
        "desc": "This item is one of the chains Kurapika uses in the anime Hunter X Hunter.",
        "img": "conjuration.gif",
        "price": "10,000,000",
        "is_in_cart": False,
        "subsection": "Hunter-x-Hunter",
        "section": "Anime",
    },
    {
        "name": "Greed Island the video game",
        "desc": "This item is a very dangerous video game from the world of Hunter X Hunter.",
        "img": "greed island.jpg",
        "price": "8,000,000,000",
        "is_in_cart": False,
        "subsection": "Hunter-x-Hunter",
        "section": "Anime",
    },
    {
        "name": "Ichigo Bankai",
        "desc": "This item is from the anime called BLEACH and the second form Zanpakuto.",
        "img": "Ichigo Bankai.jpg",
        "price": "100,000,000",
        "is_in_cart": False,
        "subsection": "BLEACH",
        "section": "Anime",
    },
    {
        "name": "Sukuna Ryomen Finger",
        "desc": "This item is from the anime called Jujutsu Kaisen",
        "img": "finger.jpg",
        "price": "200,000,000,000",
        "is_in_cart": False,
        "subsection": "Jujutsu-Kaisen",
        "section": "Anime",
    },
    {
        "name": "Kisame's Blade, 'Samehada'",
        "desc": "this item is one of the most dangerous weapons of the Seven Ninja Swordsmen blades in Naruto",
        "img": "samehada.jpg",
        "price": "20,000,050",
        "is_in_cart": False,
        "subsection": "Naruto",
        "section": "Anime",
    },
    {
        "name": "The Deathnote Notebook",
        "desc": "This Notebook is a very dangerous notebook where whoever's name is written in it, they die shortly after.",
        "img": "deathnote.jpg",
        "price": "200,000,000,000",
        "is_in_cart": False,
        "subsection": "DeathNote",
        "section": "Anime",
    },
]

FEATURED = [
    {
        "name": "Masterball",
        "desc": "Invented by Silph Co, Type of pokeball that can catch any wild pokemon without fail.",
        "img": "masterBall",
        "price": "999.99",
        "is_in_cart": False,
    }
]
